### ISSUE TITLE
Add AL2S CloudConnect handler 

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/AMHandlers#52]
Tasks:
* [x] 1. Experiment with OESS API commands for setting up L3VPN Connections for Cloud Connect
* [x] 2. Create Ansible playbooks for OESS Cloud Connect service
* [x] 3. Design Cloud Connect sliver model
* [x] 4. Add cloud_connect_handler.py to handle the Cloud Connect sliver and invoke the Ansible playbooks

**Comment by xi-yang** [comment]
Initial success of create AL2S L3VPN Cloud Connect service and BGP peering with AWS DirectConnect service.

<img width="1340" alt="Screen Shot 2022-07-14 at 11 20 53 AM" src="https://user-images.githubusercontent.com/6596456/179236129-8cd76f06-1615-4188-a28e-7a0f34042636.png">

<img width="1197" alt="Screen Shot 2022-07-14 at 11 20 33 AM" src="https://user-images.githubusercontent.com/6596456/179236146-db04c93b-3464-4bfa-bace-26a2ed2e9ea9.png">

**Comment by zlion** [comment]
Completed the experiment on creation of L3 connection with OESS APIs. The methods of vrf.cgi: "provision", "get_vrts", "remove", returns successful in my test script.

**Comment by xi-yang** [comment]
@zlion Let's work together on https://github.com/fabric-testbed/information-model-utils/issues/46

Please review the scan_net and map the OESS API calls. I will take care of the modeling.

**Comment by xi-yang** [comment]
@zlion Can you add update for Task# 2 with details to the issue comment here?

**Comment by zlion** [comment]
So far so good. Wrapping about the ansible playbook and checking in today.

**Comment by zlion** [comment]
Status update:
- Added the new handler code for al2s network. 
- Finished the initial version of source code.
- At the final stage of testing.

**Comment by xi-yang** [comment]
@zlion I do not see the source code checked in for al2s_hanlder. 

Once that code is checked, add unit test cases with pseudo-code al2s sliver so that Ilya can use it for adding the actual sliver structure in FIM.

**Comment by zlion** [comment]
The new code has been committed to the branch lzhang9-staging for reviewing.

The inventory file created on local is as follows.

[localhost]
localhost oess_url=https://al2s.net.internet2.edu//oess/services-kerb
localhost oess_user=
localhost oess_passwd=

**Comment by zlion** [comment]
The test case "testl2cloud" should already do that. Let me try it again and
let you know.

**Comment by zlion** [comment]
Unit tests have been updated to adopt to the recent change of fabric-fit-1.4.0rc2.

**Comment by xi-yang** [comment]
I saw a few places on oess_handler.py still having typos like `NetHandlerException` instead of `OessHandlerException`. @zlion Please review the code and run more tests. 

Also coordinate with Komal to see if support for methods like Modify is required or can be excluded from the orchestrator logic.

**Comment by xi-yang** [comment]
I tried the unit test with the following lines added in inventory file.
```
[localhost]
localhost oess_url="https://al2s.net.internet2.edu//oess/services-kerb"
localhost oess_user=xxx
localhost oess_passwd=yyy
```

I got error
```fabric_am.util.ansible_helper.PlaybookException: Playbook has failed tasks: Failed to connect to the host via ssh: Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.```

Anything I missed.

**Comment by xi-yang** [comment]
We should try using `connection: local` instead of ssh into localhost for actual deployment. 

<img width="808" alt="Screen Shot 2022-12-30 at 12 53 35 PM" src="https://user-images.githubusercontent.com/6596456/210099175-042bd6cf-9ce3-45ba-81b6-ff80f0018e21.png">



When this, I was able to run the sensible playbook from command line and got correct results.

```
ansible-playbook -i ./fabric_am/playbooks/inventory -e '{"name": "al2s_l3_directconn_test", "description": "al2s_l3_directconn_test", "op": "create", "level": "L3", "asn": "55038", "l3_endpoints": [{"node": "agg4.ashb.net.internet2.edu", "bandwidth": 1000, "interface": "HundredGigE0/0/0/7", "tag": "2", "jumbo": 1, "cloud_account_id": "296256999979", "peers": [{"bfd": 0, "ip_version": "ipv4", "peer_ip": "192.168.1.1/30", "peer_asn": "64512", "local_ip": "192.168.1.2/30", "md5_key": "0xzsEwC7xk6c1fK_h.xHyAdx"}]}, {"node": "agg4.sanj.net.internet2.edu", "bandwidth": 1000, "interface": "TenGigE0/0/0/12/2", "tag": "2", "jumbo": 1, "cloud_account_id": "296256999979", "peers": [{"bfd": 0, "ip_version": "ipv4", "peer_ip": "192.168.2.1/30", "peer_asn": "64512", "local_ip": "192.168.2.2/30", "md5_key": "0xzsEwC7xk6c1fK_h.xHyAdx"}]}]}' ./fabric_am/playbooks/al2s_oess.yml
```

However, I still had some problem to do this directly from the AMHandler code. @zlion

**Comment by zlion** [comment]
@xi-yang 
I set up ubuntu VM to investigate the above issue of running playbook locally. The easiest way to fix is to add one line to the inventory file as below.

```
[localhost]
localhost oess_url=https://al2s.net.internet2.edu//oess/services-kerb
localhost oess_user=
localhost oess_passwd=
localhost ansible_connection=local
```

Let me know if it works in your dev enviroment.

**Comment by xi-yang** [comment]
I further changed [localhost] into `[fabric_site_al2s]` to be consistent with other blocks in the inventory file. 

I have no issue to execute the ansible playbook from CLI but the AMHandler code still raised error `The following modules failed to execute: ansible.legacy.setup`. This is likely due to my Python environment, but I could not figure out why. @kthare10 Do you have any idea how this error could happen.

**Comment by xi-yang** [comment]
Never mind. I found the cause of problem. Liang updated the python interpreter config. The config yaml has been reverted to the default.

<img width="532" alt="Screen Shot 2023-01-03 at 9 49 33 AM" src="https://user-images.githubusercontent.com/6596456/210381237-d5cd6c0f-c941-4a86-9427-f64c2ae84621.png">

**Comment by kthare10** [comment]
@xi-yang - I suspect this could be because the Python Interpreter being explicitly passed in oess handler.
Could you please remove `ansible_python_interpreter` argument when instantiating the `AnsibleHelper` object and try the test again?

I added this for VM Handler because different python versions on Head Node but it's not needed for NetHandler/OessHandler.

```
            ansible_helper = AnsibleHelper(inventory_path=inventory_path, logger=self.get_logger(),
                                           ansible_python_interpreter=self.get_ansible_python_interpreter())
```

**Comment by xi-yang** [comment]
Bug fix verified and code merged into rel1.4.
