### ISSUE TITLE
Add net_handler modify support

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/AMHandlers#62]
* [x] 1. Parse modified_sliver data into into Ansible data
* [x] 2. Update ansible playbook to support modify 
* [x] 3. Unit test for network service modify that supports addition and removal of interfaces for l2bridge, l2ptp, l2sts, fabnetv4/v6 and portmirror services.

**Comment by xi-yang** [comment]
@kthare10 @ibaldin Can you review the unit / sliver data structure in my network service modify unit test and see if that is correct? It did pass the test. Just want to make sure I am following the "formal" procedure.

https://github.com/fabric-testbed/AMHandlers/blob/537033140aa351011174e6863d643ab2ef04236a/fabric_am/test/test_network_handler.py#L254-L367

**Comment by kthare10** [comment]
@xi-yang - 
`test_network_handler.py` - Modifications to slivers are sent as a separate sliver than the sliver for the create.
`test_L2Bridge_Modify`:  Sliver object after line 323 for modify should be created afresh and not modify the same sliver used in create. 
```
modified_sliver = NetworkServiceSliver()
.... # build all the updates, copy not modified interfaces from the base sliver
updated_unit.set_modified(modified=modified_sliver)
.....
```
`network_handler.py::modify` -  Both the currently provisioned sliver(`sliver`) and updated sliver(`modified_sliver`) are available at the AM.
I have following suggestion to handle the difference. Sorry if I mis understood, code block `218` - `234` still uses the current sliver object so changes might not reflect. Please correct me if I am wrong. 
```
sliver = unit.get_sliver()
modified_sliver = unit.get_modified()
# Compute the sliver difference
diff = sliver.diff(other_sliver=modified_sliver)
if diff is not None:
      # Modify topology
      for x in diff.added.interfaces:
          # Connect the interfaces added identified by name x
      for x in diff.removed.interfaces:
          # Disconnect the removed interfaces identified by name x
```

**Comment by xi-yang** [comment]
@kthare10 

Yes I cut corner here. It worked for network handler as it does not rely on original sliver to derive the modifications. But I will change the code following the correct process. 

Is there any issue with using `updated_unit` as the input for modify call?

**Comment by xi-yang** [comment]
Fixed and verified.
