### ISSUE TITLE
Add clean restart support to Network AM

### ISSUE THREAD

**Issue by ibaldin** [fabric-testbed/AMHandlers#64]
When we do a clean restart of an aggregate, ideally the handler should issue an 'all-clean' command to remove all services and reset the state. We don't plan to do it often, but when it is needed, it is needed.

**Comment by xi-yang** [comment]
Is this rel1.4 or rel1.5?

Ideally the orchestrator should provide a list of the existing services to clean up.

The existing NSO Ansible module cannot remove ALL services without know who they are. I may need to create a different playbook using raw restconf API.

**Comment by ibaldin** [comment]
1.4 would be ideal, but if it is a lot of work we can make it 1.5. You should talk to @kthare10 to see how site clean all works.

**Comment by xi-yang** [comment]
Found a way to nuke all NSO services in one REST call. Will do that from the code w/o Ansible. 

Only catch is that we need to put back some utility services like `services/logging` after the nuke. Just another REST call.

So yes for rel1.4.

**Comment by xi-yang** [comment]
Code done, tested and merged to rel1.4.
