### ISSUE TITLE
No null check for caps on l2 and l3 sliver data parsing

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/AMHandlers#88]
In the oess_handler.py code, there are typical blocks like
```
            caps: Capacities = interface_sliver.get_capacities()            
            ...
            endpoint['bandwidth'] = caps.bw
```

Codes like this should have applied null checking. we have seen NoneType exceptions in tests when no Capabilities are defined for endpoints. Matter of fact is that non-cloud ports do not accept bandwidth > 0. So users either input Capabilities(bw=0) no Capabilities at all. We should accommodate both cases.

**Comment by zlion** [comment]
The latest code  in the main branch has checking such as,

            if caps is not None and caps.bw is not None:
                endpoint['bandwidth'] = caps.bw * 1000      # specified in Mbps

If that is sufficient, this issue can be closed.
