### ISSUE TITLE
OESS ARM label change for cloud facilityPort

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/AMHandlers#89]
Currently the oess_scan generate a FacilityPort like the below.

```
    <node id="78">
      <data key="d0">6b1b07bb-9805-482f-9d06-101d9e8e8c0d</data>
      <data key="d1">ConnectionPoint</data>
      <data key="d2">port+al2s:agg3.dall3.net.internet2.edu:TenGigE0/0/0/11/2:Cloud_Facility_AWS:facility_port</data>
      <data key="d3">AWS_US_East__Dallas__agg3.dall3.net.internet2.edu_TenGigE0/0/0/11/2</data>
      <data key="d4">FacilityPort</data>
      <data key="d6">{"bw": 10}</data>
      <data key="d7">{"device_name": "US East (Dallas)", "local_name": "agg3.dall3.net.internet2.edu:TenGigE0/0/0/11/2:peer", "vlan_range": ["1-4095", "1-4095"]}</data>
      <data key="d8">false</data>
      <data key="d13">PDP DALL3-CONN-AWS-3</data>
    </node>
```

* [ ] 1. `"d7"` is the labels. We will need to change that into the below.
```
{"device_name": "agg3.dall3.net.internet2.edu", "local_name": "TenGigE0/0/0/11/2", "vlan_range": ["1-4095", "1-4095"], "region": "us-east-2"}
```
* [ ] 2. We will also need to translate host connection names like `"US East (Dallas)"` into the normally known `region` names. This has to be through a static mapping that is either configured into the python code or an external config file. (A separate python file could be find.) 
```
CLOUD_REGION_NAME_MAP:
    US East (Virginia): us-east-1
    US East (Ohio): us-east-2
    ...
    US East (Dallas): us-east-2
```

* [ ] 3. Also rename the `site` from `Internet2` into `AL2S` in the below line. 
```
        site_name = "Internet2"
```

**Comment by zlion** [comment]
@xi-yang 
Hi, could I have more information about this problem? 
- Where is the code of oess_scan? 
- What is the module the oess_scan is calling: amhandler or  fimutil?

**Comment by xi-yang** [comment]
@zlion My mistake. This should be in the `information-model-utils` repo. Also I should be responsible this part of code. You can just focused on getting Internet2 NOC fixing the API data.
